version: '3.8'
services:
  mysqlDB:
    image: mysql:latest
    container_name: spring-txn-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql  # Volume configuration for MySQL data
volumes:
  mysql-data:  # Define a named volume for MySQL data persistence